server:
  port: 8082
spring:
  datasource: # ????????
    type: com.zaxxer.hikari.HikariDataSource      # ???????????????????????druid
    driver-class-name: com.mysql.jdbc.Driver      # mysql/MariaDB ?????????
    url: jdbc:mysql://101.42.139.217:3306/myhr?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: a22581034
mybatis:
  type-aliases-package: com.example.sql_filter.model.pojo       # ??pojo???????
  mapper-locations: classpath:/mapper/*.xml    # mapper????